### ISSUE TITLE
 please update with github release on webstore

### ISSUE THREAD

**Issue by fisforfaheem** [warren-bank/fork-crx-PrivacyPass-challenge-bypass#1]
Use disabled extensions
If you need to use a disabled extension, you can contact the extension’s developer and ask them to upload their extension to the Chrome Web Store. This will allow you, and other people who use Chrome, to install that extension from the Chrome Web Store, or if you already have it installed, to manually re-enable it from your list of extensions.

**Comment by warren-bank** [comment]
It's my own personal position.. that I don't participate in walled garden ecosystems. The extensions that I release can be used in browsers that don't enforce their own marketplace. The code in this fork is available to the upstream project to merge (or cherry pick) at their discretion.. and they can release extensions that are blessed by the various marketplaces. I have no intention to do so.
